

MAP_NAME = "Uplinks"

MAP_ICON_HOST = 130

MAP_ICON_CLOUD = 4

DASHBOARD_NAME = "Uplinks"

DASHBOARD_NAME_BY_LOCATION = "Uplinks (by location)"

DASHBOARD_NAME_BY_PROVIDER = "Uplinks by providers"

PROVIDERS_FOR_SUMMARY = []

UPLINKS_AGGREGATE_HOST_PREFIX = "Uplinks "

UPLINKS_AGGREGATE_GROUP = "Uplinks"

THRESHOLD_PERCENT_WARN = 90

THRESHOLD_PERCENT_HIGH = 100

UPLINK_UTIL_WARN_PERCENT = 70

UPLINK_UTIL_CRIT_PERCENT = 85

UPLINK_UTIL_WARN_PERIOD = "10m"

UPLINK_UTIL_CRIT_PERIOD = "5m"

TRIGGER_DESC_UTIL_WARN_SUFFIX = "Uplink utilization high ({}%, avg {})".format(
    UPLINK_UTIL_WARN_PERCENT, UPLINK_UTIL_WARN_PERIOD
)

TRIGGER_DESC_UTIL_CRIT_SUFFIX = "Uplink utilization critical ({}%, avg {})".format(
    UPLINK_UTIL_CRIT_PERCENT, UPLINK_UTIL_CRIT_PERIOD
)

TRIGGER_TAG_NAME = "scripts"

TRIGGER_TAG_VALUE = "automatization"

TRIGGER_FUNCTION_PERIOD = "15m"

TRIGGER_DESC_90_SUFFIX = "Commit rate exceeded ({}%)".format(THRESHOLD_PERCENT_WARN)

TRIGGER_DESC_100_SUFFIX = "Commit rate exceeded (100%)"

SLA_TRIGGER_FUNCTION_PERIOD = "1h"

TRIGGER_DESC_SLA_BREACH_SUFFIX = "SLA breach: >= 100% of commit for {}".format(
    SLA_TRIGGER_FUNCTION_PERIOD
)

SLA_TRIGGER_TAG_NAME = "sla"

SLA_TRIGGER_TAG_VALUE = "true"

SLA_EFFECTIVE_DATE_UTC = 1772323200

LINK_COLOR_WARN = "DDBB00"

LINK_COLOR_HIGH = "DD0000"

THRESHOLD_ITEM_KEY = "net.if.threshold"

UPLINK_VRF_NAME = "internet"

NETBOX_AUTOMATION_TAG = TRIGGER_TAG_VALUE

PROJECT_PROVIDER_SLO_PERCENT = 99.95
